import 'package:flutter/material.dart';
const Color kLightBlueBackgroundColor= Color(0xFF33b6ff);
const Color kDarkBlueBackgroundColor=Color.fromRGBO(0, 109, 170, 1);
const Color kLightRedColor=Color(0xffe58787);
const Color kLightGreenColor=Color(0xff87e590);
const Color kLightBlueColor=Color(0xff6fcbfe);
const Color kDarkBlueColor=Color(0xff007ca4);
const Color kNextButtonColor=Color(0xff00c1fe);
const Color kPurpleColor= Color(0xff7a59ff);
const Color kPurpleShadowColor=Color(0xFFB4A2ff);
const Color kBlueShadowColor=Color(0xFFA5DFFD);